// web/src/components/Topbar.tsx
import { useWorkspace } from "../store";
import type { AppName } from "../types";

const APPS: Record<AppName, { name: string; icon: string; grad: string }> = {
  boards: { name: "Boards", icon: "◫", grad: "linear-gradient(135deg,#12c2ae,#0e9e90)" },
  base: { name: "Base", icon: "▦", grad: "linear-gradient(135deg,#f0a020,#e2445c)" },
  time: { name: "Time", icon: "◷", grad: "linear-gradient(135deg,#3b5bdb,#2f9be0)" },
  team: { name: "Team", icon: "👥", grad: "linear-gradient(135deg,#a23bc7,#7048e8)" },
};

export function Topbar({ app, onApp }: { app: AppName; onApp: (a: AppName) => void }) {
  const { state, user, readOnly, signOut } = useWorkspace();
  const a = APPS[app];
  const space = state?.spaces.find((s) => s.id === state.activeSpace);

  return (
    <header className="topbar">
      <div className="app-switcher">
        {(Object.keys(APPS) as AppName[]).map((k) => (
          <button key={k} className={"app-tile" + (k === app ? " active" : "")} title={APPS[k].name}
            onClick={() => onApp(k)} style={{ background: APPS[k].grad }}>
            {APPS[k].icon}
          </button>
        ))}
      </div>
      <div className="logo"><span className="mark" style={{ background: a.grad }}>{a.icon}</span><b>{a.name}</b></div>
      <span className="workspace">{space?.name || "My Workspace"}</span>
      {readOnly && <span className="ro-pill">Read-only</span>}
      <div className="spacer" />
      <button className="avatar" title={user?.name} onClick={signOut}>🧔</button>
    </header>
  );
}

// web/components/Topbar.vue
<template>
  <header class="topbar">
    <div class="app-switcher">
      <button v-for="(meta, key) in APPS" :key="key" class="app-tile" :class="{ active: key === app }"
        :title="meta.name" :style="{ background: meta.grad }" @click="$emit('update:app', key)">
        {{ meta.icon }}
      </button>
    </div>
    <div class="logo"><span class="mark" :style="{ background: APPS[app].grad }">{{ APPS[app].icon }}</span><b>{{ APPS[app].name }}</b></div>
    <span class="workspace">{{ spaceName }}</span>
    <span v-if="readOnly" class="ro-pill">Read-only</span>
    <div class="spacer" />
    <button class="avatar" :title="user?.name" @click="signOut">🧔</button>
  </header>
</template>

<script setup lang="ts">
import { computed } from "vue";
import type { AppName } from "~/types";

const props = defineProps<{ app: AppName }>();
defineEmits<{ "update:app": [AppName] }>();

const { workspace, user, readOnly, signOut } = useWorkspace();

const APPS: Record<AppName, { name: string; icon: string; grad: string }> = {
  boards: { name: "Boards", icon: "◫", grad: "linear-gradient(135deg,#12c2ae,#0e9e90)" },
  base: { name: "Base", icon: "▦", grad: "linear-gradient(135deg,#f0a020,#e2445c)" },
  time: { name: "Time", icon: "◷", grad: "linear-gradient(135deg,#3b5bdb,#2f9be0)" },
  team: { name: "Team", icon: "👥", grad: "linear-gradient(135deg,#a23bc7,#7048e8)" },
};

const spaceName = computed(() => {
  const w = workspace.value;
  return w?.spaces.find((s) => s.id === w.activeSpace)?.name || "My Workspace";
});
void props;
</script>
