// web/src/App.tsx
import { useState } from "react";
import { useWorkspace } from "./store";
import { AuthScreen } from "./components/AuthScreen";
import { Sidebar } from "./components/Sidebar";
import { Topbar } from "./components/Topbar";
import { BoardView } from "./components/BoardView";
import type { AppName } from "./types";

export function App() {
  const { user, state, booting } = useWorkspace();
  const [app, setApp] = useState<AppName>("boards");

  if (booting) return <div className="boot">Loading…</div>;
  if (!user) return <AuthScreen />;

  return (
    <div className="app">
      <Topbar app={app} onApp={setApp} />
      <div className="body">
        <Sidebar />
        <main className="main">
          {!state ? (
            <div className="empty">No workspace yet.</div>
          ) : app === "boards" ? (
            <BoardView />
          ) : (
            <div className="empty">
              <h2>{app[0].toUpperCase() + app.slice(1)}</h2>
              <p>This screen is being ported to the new stack next.</p>
            </div>
          )}
        </main>
      </div>
    </div>
  );
}

// web/app.vue
<template>
  <div v-if="booting" class="boot">Loading…</div>
  <AuthScreen v-else-if="!user" />
  <div v-else class="app">
    <Topbar :app="app" @update:app="app = $event" />
    <div class="body">
      <Sidebar />
      <main class="main">
        <BoardView v-if="app === 'boards' && workspace" />
        <div v-else class="empty">
          <h2>{{ cap(app) }}</h2>
          <p>This screen is being ported to the new stack next.</p>
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import type { AppName } from "~/types";

const { user, workspace, booting, boot } = useWorkspace();
const app = ref<AppName>("boards");
const cap = (s: string) => s[0].toUpperCase() + s.slice(1);

onMounted(boot);
</script>
